// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: comment.proto

package edu.isi.backpack.metadata;

public final class CommentProtos {
    private CommentProtos() {
    }

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    }

    public interface CommentOrBuilder extends com.google.protobuf.MessageOrBuilder {

        // required string text = 1;
        /**
         * <code>required string text = 1;</code>
         */
        boolean hasText();

        /**
         * <code>required string text = 1;</code>
         */
        java.lang.String getText();

        /**
         * <code>required string text = 1;</code>
         */
        com.google.protobuf.ByteString getTextBytes();

        // required string user = 2;
        /**
         * <code>required string user = 2;</code>
         */
        boolean hasUser();

        /**
         * <code>required string user = 2;</code>
         */
        java.lang.String getUser();

        /**
         * <code>required string user = 2;</code>
         */
        com.google.protobuf.ByteString getUserBytes();

        // required string date = 3;
        /**
         * <code>required string date = 3;</code>
         */
        boolean hasDate();

        /**
         * <code>required string date = 3;</code>
         */
        java.lang.String getDate();

        /**
         * <code>required string date = 3;</code>
         */
        com.google.protobuf.ByteString getDateBytes();
    }

    /**
     * Protobuf type {@code metadata.Comment}
     */
    public static final class Comment extends com.google.protobuf.GeneratedMessage implements
            CommentOrBuilder {
        // Use Comment.newBuilder() to construct.
        private Comment(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
            this.unknownFields = builder.getUnknownFields();
        }

        private Comment(boolean noInit) {
            this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private static final Comment defaultInstance;

        public static Comment getDefaultInstance() {
            return defaultInstance;
        }

        public Comment getDefaultInstanceForType() {
            return defaultInstance;
        }

        private final com.google.protobuf.UnknownFieldSet unknownFields;

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
            return this.unknownFields;
        }

        private Comment(com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            initFields();

            @SuppressWarnings("unused")
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
                    .newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            bitField0_ |= 0x00000001;
                            text_ = input.readBytes();
                            break;
                        }
                        case 18: {
                            bitField0_ |= 0x00000002;
                            user_ = input.readBytes();
                            break;
                        }
                        case 26: {
                            bitField0_ |= 0x00000004;
                            date_ = input.readBytes();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e.getMessage())
                        .setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return edu.isi.backpack.metadata.CommentProtos.internal_static_metadata_Comment_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
            return edu.isi.backpack.metadata.CommentProtos.internal_static_metadata_Comment_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            edu.isi.backpack.metadata.CommentProtos.Comment.class,
                            edu.isi.backpack.metadata.CommentProtos.Comment.Builder.class);
        }

        public static com.google.protobuf.Parser<Comment> PARSER = new com.google.protobuf.AbstractParser<Comment>() {
            public Comment parsePartialFrom(com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new Comment(input, extensionRegistry);
            }
        };

        @java.lang.Override
        public com.google.protobuf.Parser<Comment> getParserForType() {
            return PARSER;
        }

        private int bitField0_;

        // required string text = 1;
        public static final int TEXT_FIELD_NUMBER = 1;

        private java.lang.Object text_;

        /**
         * <code>required string text = 1;</code>
         */
        public boolean hasText() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>required string text = 1;</code>
         */
        public java.lang.String getText() {
            java.lang.Object ref = text_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    text_ = s;
                }
                return s;
            }
        }

        /**
         * <code>required string text = 1;</code>
         */
        public com.google.protobuf.ByteString getTextBytes() {
            java.lang.Object ref = text_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString
                        .copyFromUtf8((java.lang.String) ref);
                text_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        // required string user = 2;
        public static final int USER_FIELD_NUMBER = 2;

        private java.lang.Object user_;

        /**
         * <code>required string user = 2;</code>
         */
        public boolean hasUser() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        /**
         * <code>required string user = 2;</code>
         */
        public java.lang.String getUser() {
            java.lang.Object ref = user_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    user_ = s;
                }
                return s;
            }
        }

        /**
         * <code>required string user = 2;</code>
         */
        public com.google.protobuf.ByteString getUserBytes() {
            java.lang.Object ref = user_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString
                        .copyFromUtf8((java.lang.String) ref);
                user_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        // required string date = 3;
        public static final int DATE_FIELD_NUMBER = 3;

        private java.lang.Object date_;

        /**
         * <code>required string date = 3;</code>
         */
        public boolean hasDate() {
            return ((bitField0_ & 0x00000004) == 0x00000004);
        }

        /**
         * <code>required string date = 3;</code>
         */
        public java.lang.String getDate() {
            java.lang.Object ref = date_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    date_ = s;
                }
                return s;
            }
        }

        /**
         * <code>required string date = 3;</code>
         */
        public com.google.protobuf.ByteString getDateBytes() {
            java.lang.Object ref = date_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString
                        .copyFromUtf8((java.lang.String) ref);
                date_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private void initFields() {
            text_ = "";
            user_ = "";
            date_ = "";
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized != -1)
                return isInitialized == 1;

            if (!hasText()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasUser()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasDate()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeBytes(1, getTextBytes());
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeBytes(2, getUserBytes());
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                output.writeBytes(3, getDateBytes());
            }
            getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1)
                return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream.computeBytesSize(1, getTextBytes());
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream.computeBytesSize(2, getUserBytes());
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                size += com.google.protobuf.CodedOutputStream.computeBytesSize(3, getDateBytes());
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @java.lang.Override
        protected java.lang.Object writeReplace() throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static edu.isi.backpack.metadata.CommentProtos.Comment parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static edu.isi.backpack.metadata.CommentProtos.Comment parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static edu.isi.backpack.metadata.CommentProtos.Comment parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static edu.isi.backpack.metadata.CommentProtos.Comment parseFrom(byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static edu.isi.backpack.metadata.CommentProtos.Comment parseFrom(
                java.io.InputStream input) throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static edu.isi.backpack.metadata.CommentProtos.Comment parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static edu.isi.backpack.metadata.CommentProtos.Comment parseDelimitedFrom(
                java.io.InputStream input) throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }

        public static edu.isi.backpack.metadata.CommentProtos.Comment parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static edu.isi.backpack.metadata.CommentProtos.Comment parseFrom(
                com.google.protobuf.CodedInputStream input) throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static edu.isi.backpack.metadata.CommentProtos.Comment parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder(edu.isi.backpack.metadata.CommentProtos.Comment prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code metadata.Comment}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                edu.isi.backpack.metadata.CommentProtos.CommentOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                return edu.isi.backpack.metadata.CommentProtos.internal_static_metadata_Comment_descriptor;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
                return edu.isi.backpack.metadata.CommentProtos.internal_static_metadata_Comment_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                edu.isi.backpack.metadata.CommentProtos.Comment.class,
                                edu.isi.backpack.metadata.CommentProtos.Comment.Builder.class);
            }

            // Construct using
            // edu.isi.backpack.metadata.CommentProtos.Comment.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }

            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                text_ = "";
                bitField0_ = (bitField0_ & ~0x00000001);
                user_ = "";
                bitField0_ = (bitField0_ & ~0x00000002);
                date_ = "";
                bitField0_ = (bitField0_ & ~0x00000004);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
                return edu.isi.backpack.metadata.CommentProtos.internal_static_metadata_Comment_descriptor;
            }

            public edu.isi.backpack.metadata.CommentProtos.Comment getDefaultInstanceForType() {
                return edu.isi.backpack.metadata.CommentProtos.Comment.getDefaultInstance();
            }

            public edu.isi.backpack.metadata.CommentProtos.Comment build() {
                edu.isi.backpack.metadata.CommentProtos.Comment result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public edu.isi.backpack.metadata.CommentProtos.Comment buildPartial() {
                edu.isi.backpack.metadata.CommentProtos.Comment result = new edu.isi.backpack.metadata.CommentProtos.Comment(
                        this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.text_ = text_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.user_ = user_;
                if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
                    to_bitField0_ |= 0x00000004;
                }
                result.date_ = date_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof edu.isi.backpack.metadata.CommentProtos.Comment) {
                    return mergeFrom((edu.isi.backpack.metadata.CommentProtos.Comment) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(edu.isi.backpack.metadata.CommentProtos.Comment other) {
                if (other == edu.isi.backpack.metadata.CommentProtos.Comment.getDefaultInstance())
                    return this;
                if (other.hasText()) {
                    bitField0_ |= 0x00000001;
                    text_ = other.text_;
                    onChanged();
                }
                if (other.hasUser()) {
                    bitField0_ |= 0x00000002;
                    user_ = other.user_;
                    onChanged();
                }
                if (other.hasDate()) {
                    bitField0_ |= 0x00000004;
                    date_ = other.date_;
                    onChanged();
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                if (!hasText()) {

                    return false;
                }
                if (!hasUser()) {

                    return false;
                }
                if (!hasDate()) {

                    return false;
                }
                return true;
            }

            public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                edu.isi.backpack.metadata.CommentProtos.Comment parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (edu.isi.backpack.metadata.CommentProtos.Comment) e
                            .getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            // required string text = 1;
            private java.lang.Object text_ = "";

            /**
             * <code>required string text = 1;</code>
             */
            public boolean hasText() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>required string text = 1;</code>
             */
            public java.lang.String getText() {
                java.lang.Object ref = text_;
                if (!(ref instanceof java.lang.String)) {
                    java.lang.String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
                    text_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>required string text = 1;</code>
             */
            public com.google.protobuf.ByteString getTextBytes() {
                java.lang.Object ref = text_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString
                            .copyFromUtf8((java.lang.String) ref);
                    text_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>required string text = 1;</code>
             */
            public Builder setText(java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                text_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required string text = 1;</code>
             */
            public Builder clearText() {
                bitField0_ = (bitField0_ & ~0x00000001);
                text_ = getDefaultInstance().getText();
                onChanged();
                return this;
            }

            /**
             * <code>required string text = 1;</code>
             */
            public Builder setTextBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                text_ = value;
                onChanged();
                return this;
            }

            // required string user = 2;
            private java.lang.Object user_ = "";

            /**
             * <code>required string user = 2;</code>
             */
            public boolean hasUser() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            /**
             * <code>required string user = 2;</code>
             */
            public java.lang.String getUser() {
                java.lang.Object ref = user_;
                if (!(ref instanceof java.lang.String)) {
                    java.lang.String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
                    user_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>required string user = 2;</code>
             */
            public com.google.protobuf.ByteString getUserBytes() {
                java.lang.Object ref = user_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString
                            .copyFromUtf8((java.lang.String) ref);
                    user_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>required string user = 2;</code>
             */
            public Builder setUser(java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                user_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required string user = 2;</code>
             */
            public Builder clearUser() {
                bitField0_ = (bitField0_ & ~0x00000002);
                user_ = getDefaultInstance().getUser();
                onChanged();
                return this;
            }

            /**
             * <code>required string user = 2;</code>
             */
            public Builder setUserBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                user_ = value;
                onChanged();
                return this;
            }

            // required string date = 3;
            private java.lang.Object date_ = "";

            /**
             * <code>required string date = 3;</code>
             */
            public boolean hasDate() {
                return ((bitField0_ & 0x00000004) == 0x00000004);
            }

            /**
             * <code>required string date = 3;</code>
             */
            public java.lang.String getDate() {
                java.lang.Object ref = date_;
                if (!(ref instanceof java.lang.String)) {
                    java.lang.String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
                    date_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>required string date = 3;</code>
             */
            public com.google.protobuf.ByteString getDateBytes() {
                java.lang.Object ref = date_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString
                            .copyFromUtf8((java.lang.String) ref);
                    date_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>required string date = 3;</code>
             */
            public Builder setDate(java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                date_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required string date = 3;</code>
             */
            public Builder clearDate() {
                bitField0_ = (bitField0_ & ~0x00000004);
                date_ = getDefaultInstance().getDate();
                onChanged();
                return this;
            }

            /**
             * <code>required string date = 3;</code>
             */
            public Builder setDateBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                date_ = value;
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:metadata.Comment)
        }

        static {
            defaultInstance = new Comment(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:metadata.Comment)
    }

    private static com.google.protobuf.Descriptors.Descriptor internal_static_metadata_Comment_descriptor;

    private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_metadata_Comment_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
    static {
        java.lang.String[] descriptorData = {
            "\n\rcomment.proto\022\010metadata\"3\n\007Comment\022\014\n\004"
                    + "text\030\001 \002(\t\022\014\n\004user\030\002 \002(\t\022\014\n\004date\030\003 \002(\tB,"
                    + "\n\033edu.isi.usaid.pifi.metadataB\rCommentPr" + "otos"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
            public com.google.protobuf.ExtensionRegistry assignDescriptors(
                    com.google.protobuf.Descriptors.FileDescriptor root) {
                descriptor = root;
                internal_static_metadata_Comment_descriptor = getDescriptor().getMessageTypes()
                        .get(0);
                internal_static_metadata_Comment_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                        internal_static_metadata_Comment_descriptor, new java.lang.String[] {
                                "Text", "User", "Date",
                        });
                return null;
            }
        };
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
                descriptorData, new com.google.protobuf.Descriptors.FileDescriptor[] {}, assigner);
    }

    // @@protoc_insertion_point(outer_class_scope)
}
