// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: media.proto

package edu.isi.backpack.metadata;

public final class MediaProtos {
  private MediaProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MediaOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .metadata.Media.Item items = 1;
    /**
     * <code>repeated .metadata.Media.Item items = 1;</code>
     */
    java.util.List<edu.isi.backpack.metadata.MediaProtos.Media.Item> 
        getItemsList();
    /**
     * <code>repeated .metadata.Media.Item items = 1;</code>
     */
    edu.isi.backpack.metadata.MediaProtos.Media.Item getItems(int index);
    /**
     * <code>repeated .metadata.Media.Item items = 1;</code>
     */
    int getItemsCount();
    /**
     * <code>repeated .metadata.Media.Item items = 1;</code>
     */
    java.util.List<? extends edu.isi.backpack.metadata.MediaProtos.Media.ItemOrBuilder> 
        getItemsOrBuilderList();
    /**
     * <code>repeated .metadata.Media.Item items = 1;</code>
     */
    edu.isi.backpack.metadata.MediaProtos.Media.ItemOrBuilder getItemsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code metadata.Media}
   */
  public static final class Media extends
      com.google.protobuf.GeneratedMessage
      implements MediaOrBuilder {
    // Use Media.newBuilder() to construct.
    private Media(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Media(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Media defaultInstance;
    public static Media getDefaultInstance() {
      return defaultInstance;
    }

    public Media getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Media(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                items_ = new java.util.ArrayList<edu.isi.backpack.metadata.MediaProtos.Media.Item>();
                mutable_bitField0_ |= 0x00000001;
              }
              items_.add(input.readMessage(edu.isi.backpack.metadata.MediaProtos.Media.Item.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          items_ = java.util.Collections.unmodifiableList(items_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.isi.backpack.metadata.MediaProtos.internal_static_metadata_Media_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.isi.backpack.metadata.MediaProtos.internal_static_metadata_Media_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.isi.backpack.metadata.MediaProtos.Media.class, edu.isi.backpack.metadata.MediaProtos.Media.Builder.class);
    }

    public static com.google.protobuf.Parser<Media> PARSER =
        new com.google.protobuf.AbstractParser<Media>() {
      public Media parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Media(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Media> getParserForType() {
      return PARSER;
    }

    public interface ItemOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // optional string url = 1;
      /**
       * <code>optional string url = 1;</code>
       */
      boolean hasUrl();
      /**
       * <code>optional string url = 1;</code>
       */
      java.lang.String getUrl();
      /**
       * <code>optional string url = 1;</code>
       */
      com.google.protobuf.ByteString
          getUrlBytes();

      // optional string title = 2;
      /**
       * <code>optional string title = 2;</code>
       */
      boolean hasTitle();
      /**
       * <code>optional string title = 2;</code>
       */
      java.lang.String getTitle();
      /**
       * <code>optional string title = 2;</code>
       */
      com.google.protobuf.ByteString
          getTitleBytes();

      // optional string filename = 3;
      /**
       * <code>optional string filename = 3;</code>
       */
      boolean hasFilename();
      /**
       * <code>optional string filename = 3;</code>
       */
      java.lang.String getFilename();
      /**
       * <code>optional string filename = 3;</code>
       */
      com.google.protobuf.ByteString
          getFilenameBytes();

      // optional string pub_date = 4;
      /**
       * <code>optional string pub_date = 4;</code>
       */
      boolean hasPubDate();
      /**
       * <code>optional string pub_date = 4;</code>
       */
      java.lang.String getPubDate();
      /**
       * <code>optional string pub_date = 4;</code>
       */
      com.google.protobuf.ByteString
          getPubDateBytes();

      // repeated string categories = 5;
      /**
       * <code>repeated string categories = 5;</code>
       */
      java.util.List<java.lang.String>
      getCategoriesList();
      /**
       * <code>repeated string categories = 5;</code>
       */
      int getCategoriesCount();
      /**
       * <code>repeated string categories = 5;</code>
       */
      java.lang.String getCategories(int index);
      /**
       * <code>repeated string categories = 5;</code>
       */
      com.google.protobuf.ByteString
          getCategoriesBytes(int index);

      // optional string source = 6;
      /**
       * <code>optional string source = 6;</code>
       */
      boolean hasSource();
      /**
       * <code>optional string source = 6;</code>
       */
      java.lang.String getSource();
      /**
       * <code>optional string source = 6;</code>
       */
      com.google.protobuf.ByteString
          getSourceBytes();

      // optional .metadata.Media.Item.Type type = 7;
      /**
       * <code>optional .metadata.Media.Item.Type type = 7;</code>
       */
      boolean hasType();
      /**
       * <code>optional .metadata.Media.Item.Type type = 7;</code>
       */
      edu.isi.backpack.metadata.MediaProtos.Media.Item.Type getType();

      // optional string thumbnail = 8;
      /**
       * <code>optional string thumbnail = 8;</code>
       */
      boolean hasThumbnail();
      /**
       * <code>optional string thumbnail = 8;</code>
       */
      java.lang.String getThumbnail();
      /**
       * <code>optional string thumbnail = 8;</code>
       */
      com.google.protobuf.ByteString
          getThumbnailBytes();

      // optional string description = 9;
      /**
       * <code>optional string description = 9;</code>
       */
      boolean hasDescription();
      /**
       * <code>optional string description = 9;</code>
       */
      java.lang.String getDescription();
      /**
       * <code>optional string description = 9;</code>
       */
      com.google.protobuf.ByteString
          getDescriptionBytes();

      // optional string language = 10;
      /**
       * <code>optional string language = 10;</code>
       */
      boolean hasLanguage();
      /**
       * <code>optional string language = 10;</code>
       */
      java.lang.String getLanguage();
      /**
       * <code>optional string language = 10;</code>
       */
      com.google.protobuf.ByteString
          getLanguageBytes();
    }
    /**
     * Protobuf type {@code metadata.Media.Item}
     */
    public static final class Item extends
        com.google.protobuf.GeneratedMessage
        implements ItemOrBuilder {
      // Use Item.newBuilder() to construct.
      private Item(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Item(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Item defaultInstance;
      public static Item getDefaultInstance() {
        return defaultInstance;
      }

      public Item getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Item(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                url_ = input.readBytes();
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                title_ = input.readBytes();
                break;
              }
              case 26: {
                bitField0_ |= 0x00000004;
                filename_ = input.readBytes();
                break;
              }
              case 34: {
                bitField0_ |= 0x00000008;
                pubDate_ = input.readBytes();
                break;
              }
              case 42: {
                if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                  categories_ = new com.google.protobuf.LazyStringArrayList();
                  mutable_bitField0_ |= 0x00000010;
                }
                categories_.add(input.readBytes());
                break;
              }
              case 50: {
                bitField0_ |= 0x00000010;
                source_ = input.readBytes();
                break;
              }
              case 56: {
                int rawValue = input.readEnum();
                edu.isi.backpack.metadata.MediaProtos.Media.Item.Type value = edu.isi.backpack.metadata.MediaProtos.Media.Item.Type.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(7, rawValue);
                } else {
                  bitField0_ |= 0x00000020;
                  type_ = value;
                }
                break;
              }
              case 66: {
                bitField0_ |= 0x00000040;
                thumbnail_ = input.readBytes();
                break;
              }
              case 74: {
                bitField0_ |= 0x00000080;
                description_ = input.readBytes();
                break;
              }
              case 82: {
                bitField0_ |= 0x00000100;
                language_ = input.readBytes();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
            categories_ = new com.google.protobuf.UnmodifiableLazyStringList(categories_);
          }
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.isi.backpack.metadata.MediaProtos.internal_static_metadata_Media_Item_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.isi.backpack.metadata.MediaProtos.internal_static_metadata_Media_Item_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.isi.backpack.metadata.MediaProtos.Media.Item.class, edu.isi.backpack.metadata.MediaProtos.Media.Item.Builder.class);
      }

      public static com.google.protobuf.Parser<Item> PARSER =
          new com.google.protobuf.AbstractParser<Item>() {
        public Item parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Item(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Item> getParserForType() {
        return PARSER;
      }

      /**
       * Protobuf enum {@code metadata.Media.Item.Type}
       */
      public enum Type
          implements com.google.protobuf.ProtocolMessageEnum {
        /**
         * <code>UNKNOWN = 0;</code>
         */
        UNKNOWN(0, 0),
        /**
         * <code>HTML = 1;</code>
         */
        HTML(1, 1),
        /**
         * <code>VIDEO = 2;</code>
         */
        VIDEO(2, 2),
        /**
         * <code>AUDIO = 3;</code>
         */
        AUDIO(3, 3),
        ;

        /**
         * <code>UNKNOWN = 0;</code>
         */
        public static final int UNKNOWN_VALUE = 0;
        /**
         * <code>HTML = 1;</code>
         */
        public static final int HTML_VALUE = 1;
        /**
         * <code>VIDEO = 2;</code>
         */
        public static final int VIDEO_VALUE = 2;
        /**
         * <code>AUDIO = 3;</code>
         */
        public static final int AUDIO_VALUE = 3;


        public final int getNumber() { return value; }

        public static Type valueOf(int value) {
          switch (value) {
            case 0: return UNKNOWN;
            case 1: return HTML;
            case 2: return VIDEO;
            case 3: return AUDIO;
            default: return null;
          }
        }

        public static com.google.protobuf.Internal.EnumLiteMap<Type>
            internalGetValueMap() {
          return internalValueMap;
        }
        private static com.google.protobuf.Internal.EnumLiteMap<Type>
            internalValueMap =
              new com.google.protobuf.Internal.EnumLiteMap<Type>() {
                public Type findValueByNumber(int number) {
                  return Type.valueOf(number);
                }
              };

        public final com.google.protobuf.Descriptors.EnumValueDescriptor
            getValueDescriptor() {
          return getDescriptor().getValues().get(index);
        }
        public final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }
        public static final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptor() {
          return edu.isi.backpack.metadata.MediaProtos.Media.Item.getDescriptor().getEnumTypes().get(0);
        }

        private static final Type[] VALUES = values();

        public static Type valueOf(
            com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
          if (desc.getType() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "EnumValueDescriptor is not for this type.");
          }
          return VALUES[desc.getIndex()];
        }

        private final int index;
        private final int value;

        private Type(int index, int value) {
          this.index = index;
          this.value = value;
        }

        // @@protoc_insertion_point(enum_scope:metadata.Media.Item.Type)
      }

      private int bitField0_;
      // optional string url = 1;
      public static final int URL_FIELD_NUMBER = 1;
      private java.lang.Object url_;
      /**
       * <code>optional string url = 1;</code>
       */
      public boolean hasUrl() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string url = 1;</code>
       */
      public java.lang.String getUrl() {
        java.lang.Object ref = url_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            url_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string url = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUrlBytes() {
        java.lang.Object ref = url_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          url_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // optional string title = 2;
      public static final int TITLE_FIELD_NUMBER = 2;
      private java.lang.Object title_;
      /**
       * <code>optional string title = 2;</code>
       */
      public boolean hasTitle() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string title = 2;</code>
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            title_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string title = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // optional string filename = 3;
      public static final int FILENAME_FIELD_NUMBER = 3;
      private java.lang.Object filename_;
      /**
       * <code>optional string filename = 3;</code>
       */
      public boolean hasFilename() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string filename = 3;</code>
       */
      public java.lang.String getFilename() {
        java.lang.Object ref = filename_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            filename_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string filename = 3;</code>
       */
      public com.google.protobuf.ByteString
          getFilenameBytes() {
        java.lang.Object ref = filename_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          filename_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // optional string pub_date = 4;
      public static final int PUB_DATE_FIELD_NUMBER = 4;
      private java.lang.Object pubDate_;
      /**
       * <code>optional string pub_date = 4;</code>
       */
      public boolean hasPubDate() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string pub_date = 4;</code>
       */
      public java.lang.String getPubDate() {
        java.lang.Object ref = pubDate_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            pubDate_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string pub_date = 4;</code>
       */
      public com.google.protobuf.ByteString
          getPubDateBytes() {
        java.lang.Object ref = pubDate_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pubDate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // repeated string categories = 5;
      public static final int CATEGORIES_FIELD_NUMBER = 5;
      private com.google.protobuf.LazyStringList categories_;
      /**
       * <code>repeated string categories = 5;</code>
       */
      public java.util.List<java.lang.String>
          getCategoriesList() {
        return categories_;
      }
      /**
       * <code>repeated string categories = 5;</code>
       */
      public int getCategoriesCount() {
        return categories_.size();
      }
      /**
       * <code>repeated string categories = 5;</code>
       */
      public java.lang.String getCategories(int index) {
        return categories_.get(index);
      }
      /**
       * <code>repeated string categories = 5;</code>
       */
      public com.google.protobuf.ByteString
          getCategoriesBytes(int index) {
        return categories_.getByteString(index);
      }

      // optional string source = 6;
      public static final int SOURCE_FIELD_NUMBER = 6;
      private java.lang.Object source_;
      /**
       * <code>optional string source = 6;</code>
       */
      public boolean hasSource() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string source = 6;</code>
       */
      public java.lang.String getSource() {
        java.lang.Object ref = source_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            source_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string source = 6;</code>
       */
      public com.google.protobuf.ByteString
          getSourceBytes() {
        java.lang.Object ref = source_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          source_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // optional .metadata.Media.Item.Type type = 7;
      public static final int TYPE_FIELD_NUMBER = 7;
      private edu.isi.backpack.metadata.MediaProtos.Media.Item.Type type_;
      /**
       * <code>optional .metadata.Media.Item.Type type = 7;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional .metadata.Media.Item.Type type = 7;</code>
       */
      public edu.isi.backpack.metadata.MediaProtos.Media.Item.Type getType() {
        return type_;
      }

      // optional string thumbnail = 8;
      public static final int THUMBNAIL_FIELD_NUMBER = 8;
      private java.lang.Object thumbnail_;
      /**
       * <code>optional string thumbnail = 8;</code>
       */
      public boolean hasThumbnail() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string thumbnail = 8;</code>
       */
      public java.lang.String getThumbnail() {
        java.lang.Object ref = thumbnail_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            thumbnail_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string thumbnail = 8;</code>
       */
      public com.google.protobuf.ByteString
          getThumbnailBytes() {
        java.lang.Object ref = thumbnail_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          thumbnail_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // optional string description = 9;
      public static final int DESCRIPTION_FIELD_NUMBER = 9;
      private java.lang.Object description_;
      /**
       * <code>optional string description = 9;</code>
       */
      public boolean hasDescription() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional string description = 9;</code>
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            description_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string description = 9;</code>
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // optional string language = 10;
      public static final int LANGUAGE_FIELD_NUMBER = 10;
      private java.lang.Object language_;
      /**
       * <code>optional string language = 10;</code>
       */
      public boolean hasLanguage() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional string language = 10;</code>
       */
      public java.lang.String getLanguage() {
        java.lang.Object ref = language_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            language_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string language = 10;</code>
       */
      public com.google.protobuf.ByteString
          getLanguageBytes() {
        java.lang.Object ref = language_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          language_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        url_ = "";
        title_ = "";
        filename_ = "";
        pubDate_ = "";
        categories_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        source_ = "";
        type_ = edu.isi.backpack.metadata.MediaProtos.Media.Item.Type.UNKNOWN;
        thumbnail_ = "";
        description_ = "";
        language_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getUrlBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getTitleBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeBytes(3, getFilenameBytes());
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          output.writeBytes(4, getPubDateBytes());
        }
        for (int i = 0; i < categories_.size(); i++) {
          output.writeBytes(5, categories_.getByteString(i));
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          output.writeBytes(6, getSourceBytes());
        }
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          output.writeEnum(7, type_.getNumber());
        }
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          output.writeBytes(8, getThumbnailBytes());
        }
        if (((bitField0_ & 0x00000080) == 0x00000080)) {
          output.writeBytes(9, getDescriptionBytes());
        }
        if (((bitField0_ & 0x00000100) == 0x00000100)) {
          output.writeBytes(10, getLanguageBytes());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getUrlBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getTitleBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(3, getFilenameBytes());
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(4, getPubDateBytes());
        }
        {
          int dataSize = 0;
          for (int i = 0; i < categories_.size(); i++) {
            dataSize += com.google.protobuf.CodedOutputStream
              .computeBytesSizeNoTag(categories_.getByteString(i));
          }
          size += dataSize;
          size += 1 * getCategoriesList().size();
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(6, getSourceBytes());
        }
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(7, type_.getNumber());
        }
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(8, getThumbnailBytes());
        }
        if (((bitField0_ & 0x00000080) == 0x00000080)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(9, getDescriptionBytes());
        }
        if (((bitField0_ & 0x00000100) == 0x00000100)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(10, getLanguageBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static edu.isi.backpack.metadata.MediaProtos.Media.Item parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static edu.isi.backpack.metadata.MediaProtos.Media.Item parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static edu.isi.backpack.metadata.MediaProtos.Media.Item parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static edu.isi.backpack.metadata.MediaProtos.Media.Item parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static edu.isi.backpack.metadata.MediaProtos.Media.Item parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static edu.isi.backpack.metadata.MediaProtos.Media.Item parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static edu.isi.backpack.metadata.MediaProtos.Media.Item parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static edu.isi.backpack.metadata.MediaProtos.Media.Item parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static edu.isi.backpack.metadata.MediaProtos.Media.Item parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static edu.isi.backpack.metadata.MediaProtos.Media.Item parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(edu.isi.backpack.metadata.MediaProtos.Media.Item prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code metadata.Media.Item}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements edu.isi.backpack.metadata.MediaProtos.Media.ItemOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return edu.isi.backpack.metadata.MediaProtos.internal_static_metadata_Media_Item_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return edu.isi.backpack.metadata.MediaProtos.internal_static_metadata_Media_Item_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  edu.isi.backpack.metadata.MediaProtos.Media.Item.class, edu.isi.backpack.metadata.MediaProtos.Media.Item.Builder.class);
        }

        // Construct using edu.isi.backpack.metadata.MediaProtos.Media.Item.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          url_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          title_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          filename_ = "";
          bitField0_ = (bitField0_ & ~0x00000004);
          pubDate_ = "";
          bitField0_ = (bitField0_ & ~0x00000008);
          categories_ = com.google.protobuf.LazyStringArrayList.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000010);
          source_ = "";
          bitField0_ = (bitField0_ & ~0x00000020);
          type_ = edu.isi.backpack.metadata.MediaProtos.Media.Item.Type.UNKNOWN;
          bitField0_ = (bitField0_ & ~0x00000040);
          thumbnail_ = "";
          bitField0_ = (bitField0_ & ~0x00000080);
          description_ = "";
          bitField0_ = (bitField0_ & ~0x00000100);
          language_ = "";
          bitField0_ = (bitField0_ & ~0x00000200);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return edu.isi.backpack.metadata.MediaProtos.internal_static_metadata_Media_Item_descriptor;
        }

        public edu.isi.backpack.metadata.MediaProtos.Media.Item getDefaultInstanceForType() {
          return edu.isi.backpack.metadata.MediaProtos.Media.Item.getDefaultInstance();
        }

        public edu.isi.backpack.metadata.MediaProtos.Media.Item build() {
          edu.isi.backpack.metadata.MediaProtos.Media.Item result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public edu.isi.backpack.metadata.MediaProtos.Media.Item buildPartial() {
          edu.isi.backpack.metadata.MediaProtos.Media.Item result = new edu.isi.backpack.metadata.MediaProtos.Media.Item(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.url_ = url_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.title_ = title_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.filename_ = filename_;
          if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
            to_bitField0_ |= 0x00000008;
          }
          result.pubDate_ = pubDate_;
          if (((bitField0_ & 0x00000010) == 0x00000010)) {
            categories_ = new com.google.protobuf.UnmodifiableLazyStringList(
                categories_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.categories_ = categories_;
          if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
            to_bitField0_ |= 0x00000010;
          }
          result.source_ = source_;
          if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
            to_bitField0_ |= 0x00000020;
          }
          result.type_ = type_;
          if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
            to_bitField0_ |= 0x00000040;
          }
          result.thumbnail_ = thumbnail_;
          if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
            to_bitField0_ |= 0x00000080;
          }
          result.description_ = description_;
          if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
            to_bitField0_ |= 0x00000100;
          }
          result.language_ = language_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof edu.isi.backpack.metadata.MediaProtos.Media.Item) {
            return mergeFrom((edu.isi.backpack.metadata.MediaProtos.Media.Item)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(edu.isi.backpack.metadata.MediaProtos.Media.Item other) {
          if (other == edu.isi.backpack.metadata.MediaProtos.Media.Item.getDefaultInstance()) return this;
          if (other.hasUrl()) {
            bitField0_ |= 0x00000001;
            url_ = other.url_;
            onChanged();
          }
          if (other.hasTitle()) {
            bitField0_ |= 0x00000002;
            title_ = other.title_;
            onChanged();
          }
          if (other.hasFilename()) {
            bitField0_ |= 0x00000004;
            filename_ = other.filename_;
            onChanged();
          }
          if (other.hasPubDate()) {
            bitField0_ |= 0x00000008;
            pubDate_ = other.pubDate_;
            onChanged();
          }
          if (!other.categories_.isEmpty()) {
            if (categories_.isEmpty()) {
              categories_ = other.categories_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureCategoriesIsMutable();
              categories_.addAll(other.categories_);
            }
            onChanged();
          }
          if (other.hasSource()) {
            bitField0_ |= 0x00000020;
            source_ = other.source_;
            onChanged();
          }
          if (other.hasType()) {
            setType(other.getType());
          }
          if (other.hasThumbnail()) {
            bitField0_ |= 0x00000080;
            thumbnail_ = other.thumbnail_;
            onChanged();
          }
          if (other.hasDescription()) {
            bitField0_ |= 0x00000100;
            description_ = other.description_;
            onChanged();
          }
          if (other.hasLanguage()) {
            bitField0_ |= 0x00000200;
            language_ = other.language_;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          edu.isi.backpack.metadata.MediaProtos.Media.Item parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (edu.isi.backpack.metadata.MediaProtos.Media.Item) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // optional string url = 1;
        private java.lang.Object url_ = "";
        /**
         * <code>optional string url = 1;</code>
         */
        public boolean hasUrl() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional string url = 1;</code>
         */
        public java.lang.String getUrl() {
          java.lang.Object ref = url_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            url_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string url = 1;</code>
         */
        public com.google.protobuf.ByteString
            getUrlBytes() {
          java.lang.Object ref = url_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            url_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string url = 1;</code>
         */
        public Builder setUrl(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          url_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string url = 1;</code>
         */
        public Builder clearUrl() {
          bitField0_ = (bitField0_ & ~0x00000001);
          url_ = getDefaultInstance().getUrl();
          onChanged();
          return this;
        }
        /**
         * <code>optional string url = 1;</code>
         */
        public Builder setUrlBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          url_ = value;
          onChanged();
          return this;
        }

        // optional string title = 2;
        private java.lang.Object title_ = "";
        /**
         * <code>optional string title = 2;</code>
         */
        public boolean hasTitle() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional string title = 2;</code>
         */
        public java.lang.String getTitle() {
          java.lang.Object ref = title_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            title_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string title = 2;</code>
         */
        public com.google.protobuf.ByteString
            getTitleBytes() {
          java.lang.Object ref = title_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            title_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string title = 2;</code>
         */
        public Builder setTitle(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          title_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string title = 2;</code>
         */
        public Builder clearTitle() {
          bitField0_ = (bitField0_ & ~0x00000002);
          title_ = getDefaultInstance().getTitle();
          onChanged();
          return this;
        }
        /**
         * <code>optional string title = 2;</code>
         */
        public Builder setTitleBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          title_ = value;
          onChanged();
          return this;
        }

        // optional string filename = 3;
        private java.lang.Object filename_ = "";
        /**
         * <code>optional string filename = 3;</code>
         */
        public boolean hasFilename() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>optional string filename = 3;</code>
         */
        public java.lang.String getFilename() {
          java.lang.Object ref = filename_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            filename_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string filename = 3;</code>
         */
        public com.google.protobuf.ByteString
            getFilenameBytes() {
          java.lang.Object ref = filename_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            filename_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string filename = 3;</code>
         */
        public Builder setFilename(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          filename_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string filename = 3;</code>
         */
        public Builder clearFilename() {
          bitField0_ = (bitField0_ & ~0x00000004);
          filename_ = getDefaultInstance().getFilename();
          onChanged();
          return this;
        }
        /**
         * <code>optional string filename = 3;</code>
         */
        public Builder setFilenameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          filename_ = value;
          onChanged();
          return this;
        }

        // optional string pub_date = 4;
        private java.lang.Object pubDate_ = "";
        /**
         * <code>optional string pub_date = 4;</code>
         */
        public boolean hasPubDate() {
          return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        /**
         * <code>optional string pub_date = 4;</code>
         */
        public java.lang.String getPubDate() {
          java.lang.Object ref = pubDate_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            pubDate_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string pub_date = 4;</code>
         */
        public com.google.protobuf.ByteString
            getPubDateBytes() {
          java.lang.Object ref = pubDate_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            pubDate_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string pub_date = 4;</code>
         */
        public Builder setPubDate(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
          pubDate_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string pub_date = 4;</code>
         */
        public Builder clearPubDate() {
          bitField0_ = (bitField0_ & ~0x00000008);
          pubDate_ = getDefaultInstance().getPubDate();
          onChanged();
          return this;
        }
        /**
         * <code>optional string pub_date = 4;</code>
         */
        public Builder setPubDateBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
          pubDate_ = value;
          onChanged();
          return this;
        }

        // repeated string categories = 5;
        private com.google.protobuf.LazyStringList categories_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        private void ensureCategoriesIsMutable() {
          if (!((bitField0_ & 0x00000010) == 0x00000010)) {
            categories_ = new com.google.protobuf.LazyStringArrayList(categories_);
            bitField0_ |= 0x00000010;
           }
        }
        /**
         * <code>repeated string categories = 5;</code>
         */
        public java.util.List<java.lang.String>
            getCategoriesList() {
          return java.util.Collections.unmodifiableList(categories_);
        }
        /**
         * <code>repeated string categories = 5;</code>
         */
        public int getCategoriesCount() {
          return categories_.size();
        }
        /**
         * <code>repeated string categories = 5;</code>
         */
        public java.lang.String getCategories(int index) {
          return categories_.get(index);
        }
        /**
         * <code>repeated string categories = 5;</code>
         */
        public com.google.protobuf.ByteString
            getCategoriesBytes(int index) {
          return categories_.getByteString(index);
        }
        /**
         * <code>repeated string categories = 5;</code>
         */
        public Builder setCategories(
            int index, java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureCategoriesIsMutable();
          categories_.set(index, value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string categories = 5;</code>
         */
        public Builder addCategories(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureCategoriesIsMutable();
          categories_.add(value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string categories = 5;</code>
         */
        public Builder addAllCategories(
            java.lang.Iterable<java.lang.String> values) {
          ensureCategoriesIsMutable();
          super.addAll(values, categories_);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string categories = 5;</code>
         */
        public Builder clearCategories() {
          categories_ = com.google.protobuf.LazyStringArrayList.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string categories = 5;</code>
         */
        public Builder addCategoriesBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureCategoriesIsMutable();
          categories_.add(value);
          onChanged();
          return this;
        }

        // optional string source = 6;
        private java.lang.Object source_ = "";
        /**
         * <code>optional string source = 6;</code>
         */
        public boolean hasSource() {
          return ((bitField0_ & 0x00000020) == 0x00000020);
        }
        /**
         * <code>optional string source = 6;</code>
         */
        public java.lang.String getSource() {
          java.lang.Object ref = source_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            source_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string source = 6;</code>
         */
        public com.google.protobuf.ByteString
            getSourceBytes() {
          java.lang.Object ref = source_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            source_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string source = 6;</code>
         */
        public Builder setSource(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
          source_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string source = 6;</code>
         */
        public Builder clearSource() {
          bitField0_ = (bitField0_ & ~0x00000020);
          source_ = getDefaultInstance().getSource();
          onChanged();
          return this;
        }
        /**
         * <code>optional string source = 6;</code>
         */
        public Builder setSourceBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
          source_ = value;
          onChanged();
          return this;
        }

        // optional .metadata.Media.Item.Type type = 7;
        private edu.isi.backpack.metadata.MediaProtos.Media.Item.Type type_ = edu.isi.backpack.metadata.MediaProtos.Media.Item.Type.UNKNOWN;
        /**
         * <code>optional .metadata.Media.Item.Type type = 7;</code>
         */
        public boolean hasType() {
          return ((bitField0_ & 0x00000040) == 0x00000040);
        }
        /**
         * <code>optional .metadata.Media.Item.Type type = 7;</code>
         */
        public edu.isi.backpack.metadata.MediaProtos.Media.Item.Type getType() {
          return type_;
        }
        /**
         * <code>optional .metadata.Media.Item.Type type = 7;</code>
         */
        public Builder setType(edu.isi.backpack.metadata.MediaProtos.Media.Item.Type value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000040;
          type_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional .metadata.Media.Item.Type type = 7;</code>
         */
        public Builder clearType() {
          bitField0_ = (bitField0_ & ~0x00000040);
          type_ = edu.isi.backpack.metadata.MediaProtos.Media.Item.Type.UNKNOWN;
          onChanged();
          return this;
        }

        // optional string thumbnail = 8;
        private java.lang.Object thumbnail_ = "";
        /**
         * <code>optional string thumbnail = 8;</code>
         */
        public boolean hasThumbnail() {
          return ((bitField0_ & 0x00000080) == 0x00000080);
        }
        /**
         * <code>optional string thumbnail = 8;</code>
         */
        public java.lang.String getThumbnail() {
          java.lang.Object ref = thumbnail_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            thumbnail_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string thumbnail = 8;</code>
         */
        public com.google.protobuf.ByteString
            getThumbnailBytes() {
          java.lang.Object ref = thumbnail_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            thumbnail_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string thumbnail = 8;</code>
         */
        public Builder setThumbnail(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
          thumbnail_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string thumbnail = 8;</code>
         */
        public Builder clearThumbnail() {
          bitField0_ = (bitField0_ & ~0x00000080);
          thumbnail_ = getDefaultInstance().getThumbnail();
          onChanged();
          return this;
        }
        /**
         * <code>optional string thumbnail = 8;</code>
         */
        public Builder setThumbnailBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
          thumbnail_ = value;
          onChanged();
          return this;
        }

        // optional string description = 9;
        private java.lang.Object description_ = "";
        /**
         * <code>optional string description = 9;</code>
         */
        public boolean hasDescription() {
          return ((bitField0_ & 0x00000100) == 0x00000100);
        }
        /**
         * <code>optional string description = 9;</code>
         */
        public java.lang.String getDescription() {
          java.lang.Object ref = description_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            description_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string description = 9;</code>
         */
        public com.google.protobuf.ByteString
            getDescriptionBytes() {
          java.lang.Object ref = description_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            description_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string description = 9;</code>
         */
        public Builder setDescription(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
          description_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string description = 9;</code>
         */
        public Builder clearDescription() {
          bitField0_ = (bitField0_ & ~0x00000100);
          description_ = getDefaultInstance().getDescription();
          onChanged();
          return this;
        }
        /**
         * <code>optional string description = 9;</code>
         */
        public Builder setDescriptionBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
          description_ = value;
          onChanged();
          return this;
        }

        // optional string language = 10;
        private java.lang.Object language_ = "";
        /**
         * <code>optional string language = 10;</code>
         */
        public boolean hasLanguage() {
          return ((bitField0_ & 0x00000200) == 0x00000200);
        }
        /**
         * <code>optional string language = 10;</code>
         */
        public java.lang.String getLanguage() {
          java.lang.Object ref = language_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            language_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string language = 10;</code>
         */
        public com.google.protobuf.ByteString
            getLanguageBytes() {
          java.lang.Object ref = language_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            language_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string language = 10;</code>
         */
        public Builder setLanguage(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
          language_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string language = 10;</code>
         */
        public Builder clearLanguage() {
          bitField0_ = (bitField0_ & ~0x00000200);
          language_ = getDefaultInstance().getLanguage();
          onChanged();
          return this;
        }
        /**
         * <code>optional string language = 10;</code>
         */
        public Builder setLanguageBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
          language_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:metadata.Media.Item)
      }

      static {
        defaultInstance = new Item(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:metadata.Media.Item)
    }

    // repeated .metadata.Media.Item items = 1;
    public static final int ITEMS_FIELD_NUMBER = 1;
    private java.util.List<edu.isi.backpack.metadata.MediaProtos.Media.Item> items_;
    /**
     * <code>repeated .metadata.Media.Item items = 1;</code>
     */
    public java.util.List<edu.isi.backpack.metadata.MediaProtos.Media.Item> getItemsList() {
      return items_;
    }
    /**
     * <code>repeated .metadata.Media.Item items = 1;</code>
     */
    public java.util.List<? extends edu.isi.backpack.metadata.MediaProtos.Media.ItemOrBuilder> 
        getItemsOrBuilderList() {
      return items_;
    }
    /**
     * <code>repeated .metadata.Media.Item items = 1;</code>
     */
    public int getItemsCount() {
      return items_.size();
    }
    /**
     * <code>repeated .metadata.Media.Item items = 1;</code>
     */
    public edu.isi.backpack.metadata.MediaProtos.Media.Item getItems(int index) {
      return items_.get(index);
    }
    /**
     * <code>repeated .metadata.Media.Item items = 1;</code>
     */
    public edu.isi.backpack.metadata.MediaProtos.Media.ItemOrBuilder getItemsOrBuilder(
        int index) {
      return items_.get(index);
    }

    private void initFields() {
      items_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < items_.size(); i++) {
        output.writeMessage(1, items_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < items_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, items_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static edu.isi.backpack.metadata.MediaProtos.Media parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.isi.backpack.metadata.MediaProtos.Media parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.isi.backpack.metadata.MediaProtos.Media parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.isi.backpack.metadata.MediaProtos.Media parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.isi.backpack.metadata.MediaProtos.Media parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static edu.isi.backpack.metadata.MediaProtos.Media parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static edu.isi.backpack.metadata.MediaProtos.Media parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static edu.isi.backpack.metadata.MediaProtos.Media parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static edu.isi.backpack.metadata.MediaProtos.Media parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static edu.isi.backpack.metadata.MediaProtos.Media parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.isi.backpack.metadata.MediaProtos.Media prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code metadata.Media}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements edu.isi.backpack.metadata.MediaProtos.MediaOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.isi.backpack.metadata.MediaProtos.internal_static_metadata_Media_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.isi.backpack.metadata.MediaProtos.internal_static_metadata_Media_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.isi.backpack.metadata.MediaProtos.Media.class, edu.isi.backpack.metadata.MediaProtos.Media.Builder.class);
      }

      // Construct using edu.isi.backpack.metadata.MediaProtos.Media.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getItemsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          itemsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.isi.backpack.metadata.MediaProtos.internal_static_metadata_Media_descriptor;
      }

      public edu.isi.backpack.metadata.MediaProtos.Media getDefaultInstanceForType() {
        return edu.isi.backpack.metadata.MediaProtos.Media.getDefaultInstance();
      }

      public edu.isi.backpack.metadata.MediaProtos.Media build() {
        edu.isi.backpack.metadata.MediaProtos.Media result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public edu.isi.backpack.metadata.MediaProtos.Media buildPartial() {
        edu.isi.backpack.metadata.MediaProtos.Media result = new edu.isi.backpack.metadata.MediaProtos.Media(this);
        int from_bitField0_ = bitField0_;
        if (itemsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            items_ = java.util.Collections.unmodifiableList(items_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.items_ = items_;
        } else {
          result.items_ = itemsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.isi.backpack.metadata.MediaProtos.Media) {
          return mergeFrom((edu.isi.backpack.metadata.MediaProtos.Media)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.isi.backpack.metadata.MediaProtos.Media other) {
        if (other == edu.isi.backpack.metadata.MediaProtos.Media.getDefaultInstance()) return this;
        if (itemsBuilder_ == null) {
          if (!other.items_.isEmpty()) {
            if (items_.isEmpty()) {
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureItemsIsMutable();
              items_.addAll(other.items_);
            }
            onChanged();
          }
        } else {
          if (!other.items_.isEmpty()) {
            if (itemsBuilder_.isEmpty()) {
              itemsBuilder_.dispose();
              itemsBuilder_ = null;
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000001);
              itemsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getItemsFieldBuilder() : null;
            } else {
              itemsBuilder_.addAllMessages(other.items_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.isi.backpack.metadata.MediaProtos.Media parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.isi.backpack.metadata.MediaProtos.Media) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .metadata.Media.Item items = 1;
      private java.util.List<edu.isi.backpack.metadata.MediaProtos.Media.Item> items_ =
        java.util.Collections.emptyList();
      private void ensureItemsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          items_ = new java.util.ArrayList<edu.isi.backpack.metadata.MediaProtos.Media.Item>(items_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          edu.isi.backpack.metadata.MediaProtos.Media.Item, edu.isi.backpack.metadata.MediaProtos.Media.Item.Builder, edu.isi.backpack.metadata.MediaProtos.Media.ItemOrBuilder> itemsBuilder_;

      /**
       * <code>repeated .metadata.Media.Item items = 1;</code>
       */
      public java.util.List<edu.isi.backpack.metadata.MediaProtos.Media.Item> getItemsList() {
        if (itemsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(items_);
        } else {
          return itemsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .metadata.Media.Item items = 1;</code>
       */
      public int getItemsCount() {
        if (itemsBuilder_ == null) {
          return items_.size();
        } else {
          return itemsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .metadata.Media.Item items = 1;</code>
       */
      public edu.isi.backpack.metadata.MediaProtos.Media.Item getItems(int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);
        } else {
          return itemsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .metadata.Media.Item items = 1;</code>
       */
      public Builder setItems(
          int index, edu.isi.backpack.metadata.MediaProtos.Media.Item value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.set(index, value);
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .metadata.Media.Item items = 1;</code>
       */
      public Builder setItems(
          int index, edu.isi.backpack.metadata.MediaProtos.Media.Item.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.set(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .metadata.Media.Item items = 1;</code>
       */
      public Builder addItems(edu.isi.backpack.metadata.MediaProtos.Media.Item value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .metadata.Media.Item items = 1;</code>
       */
      public Builder addItems(
          int index, edu.isi.backpack.metadata.MediaProtos.Media.Item value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(index, value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .metadata.Media.Item items = 1;</code>
       */
      public Builder addItems(
          edu.isi.backpack.metadata.MediaProtos.Media.Item.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .metadata.Media.Item items = 1;</code>
       */
      public Builder addItems(
          int index, edu.isi.backpack.metadata.MediaProtos.Media.Item.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .metadata.Media.Item items = 1;</code>
       */
      public Builder addAllItems(
          java.lang.Iterable<? extends edu.isi.backpack.metadata.MediaProtos.Media.Item> values) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          super.addAll(values, items_);
          onChanged();
        } else {
          itemsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .metadata.Media.Item items = 1;</code>
       */
      public Builder clearItems() {
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          itemsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .metadata.Media.Item items = 1;</code>
       */
      public Builder removeItems(int index) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.remove(index);
          onChanged();
        } else {
          itemsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .metadata.Media.Item items = 1;</code>
       */
      public edu.isi.backpack.metadata.MediaProtos.Media.Item.Builder getItemsBuilder(
          int index) {
        return getItemsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .metadata.Media.Item items = 1;</code>
       */
      public edu.isi.backpack.metadata.MediaProtos.Media.ItemOrBuilder getItemsOrBuilder(
          int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);  } else {
          return itemsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .metadata.Media.Item items = 1;</code>
       */
      public java.util.List<? extends edu.isi.backpack.metadata.MediaProtos.Media.ItemOrBuilder> 
           getItemsOrBuilderList() {
        if (itemsBuilder_ != null) {
          return itemsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(items_);
        }
      }
      /**
       * <code>repeated .metadata.Media.Item items = 1;</code>
       */
      public edu.isi.backpack.metadata.MediaProtos.Media.Item.Builder addItemsBuilder() {
        return getItemsFieldBuilder().addBuilder(
            edu.isi.backpack.metadata.MediaProtos.Media.Item.getDefaultInstance());
      }
      /**
       * <code>repeated .metadata.Media.Item items = 1;</code>
       */
      public edu.isi.backpack.metadata.MediaProtos.Media.Item.Builder addItemsBuilder(
          int index) {
        return getItemsFieldBuilder().addBuilder(
            index, edu.isi.backpack.metadata.MediaProtos.Media.Item.getDefaultInstance());
      }
      /**
       * <code>repeated .metadata.Media.Item items = 1;</code>
       */
      public java.util.List<edu.isi.backpack.metadata.MediaProtos.Media.Item.Builder> 
           getItemsBuilderList() {
        return getItemsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          edu.isi.backpack.metadata.MediaProtos.Media.Item, edu.isi.backpack.metadata.MediaProtos.Media.Item.Builder, edu.isi.backpack.metadata.MediaProtos.Media.ItemOrBuilder> 
          getItemsFieldBuilder() {
        if (itemsBuilder_ == null) {
          itemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              edu.isi.backpack.metadata.MediaProtos.Media.Item, edu.isi.backpack.metadata.MediaProtos.Media.Item.Builder, edu.isi.backpack.metadata.MediaProtos.Media.ItemOrBuilder>(
                  items_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          items_ = null;
        }
        return itemsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:metadata.Media)
    }

    static {
      defaultInstance = new Media(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:metadata.Media)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_metadata_Media_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_metadata_Media_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_metadata_Media_Item_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_metadata_Media_Item_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013media.proto\022\010metadata\"\261\002\n\005Media\022#\n\005ite" +
      "ms\030\001 \003(\0132\024.metadata.Media.Item\032\202\002\n\004Item\022" +
      "\013\n\003url\030\001 \001(\t\022\r\n\005title\030\002 \001(\t\022\020\n\010filename\030" +
      "\003 \001(\t\022\020\n\010pub_date\030\004 \001(\t\022\022\n\ncategories\030\005 " +
      "\003(\t\022\016\n\006source\030\006 \001(\t\022\'\n\004type\030\007 \001(\0162\031.meta" +
      "data.Media.Item.Type\022\021\n\tthumbnail\030\010 \001(\t\022" +
      "\023\n\013description\030\t \001(\t\022\020\n\010language\030\n \001(\t\"3" +
      "\n\004Type\022\013\n\007UNKNOWN\020\000\022\010\n\004HTML\020\001\022\t\n\005VIDEO\020\002" +
      "\022\t\n\005AUDIO\020\003B(\n\031edu.isi.backpack.metadata" +
      "B\013MediaProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_metadata_Media_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_metadata_Media_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_metadata_Media_descriptor,
              new java.lang.String[] { "Items", });
          internal_static_metadata_Media_Item_descriptor =
            internal_static_metadata_Media_descriptor.getNestedTypes().get(0);
          internal_static_metadata_Media_Item_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_metadata_Media_Item_descriptor,
              new java.lang.String[] { "Url", "Title", "Filename", "PubDate", "Categories", "Source", "Type", "Thumbnail", "Description", "Language", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
